# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11mkRmStcj2bamwrk0Bvae2Pvc8lpyR0q
"""

import pandas as pd
import re
import requests
from bs4 import BeautifulSoup
url='https://sofifa.com/players?offset=0'
soup = BeautifulSoup(resp.content, 'lxml')
soup.prettify()
NAME = []
AGE = []
OVA = []
POT = []
TEAM_NAME = []
CONTRACT = []
VALUE(M) = []
WAGE(K) = []
TOTAL_STATS = []
for i in soup.findAll('td'):
  arr.append(str(i))
arr
re.sub('^<td class="col-name"><div class="bp3-text-overflow-ellipsis">','',arr[1])
df = pd.DataFrame({"Name": NAME,
                   "Age": AGE,
                   "Overall_Rating": OVA,
                   "Potential": POT,
                   "Team_Name": TEAM_NAME,
                   "Contract_Year": CONTRACT,
                   "Value(M)": VALUE,
                   "Wage(K)": WAGE,
                   "Total_Stats": TOTAL_STATS})

df.head() # Check
df.to_csv('fifa.csv') # Export the data